apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
   name: busybox
spec:
 containers:
  - image: busybox
    name: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
     - sleep
     - "3600"
 restartPolicy: Always
