apiVersion: v1
kind: Pod
metadata:
  name: yellow
  labels:
   app: multicontainers
   type: PODS
spec:
 initContainers:
   - name: init_myservice
     image: busybox
     command: ["sleep 30"]
 containers:
   - name: lemon
     image: busybox
     resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
   - name: gold
     image: redis
     resources:
      limits:
        cpu: "500m"
        memory: "128Mi"