apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
   name: busybox
spec:
 containers:
  - image: busybox
    name: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - image: redis
    name: red
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
     - sleep
     - "3600"
    envFrom:
     - configMapRef:
        name: nameoftheconfigfile
       secretRef:
         name: nameofthesecretefile

       
 restartPolicy: Always